# Generated by Django 4.1.7 on 2023-02-18 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Title')),
                ('other_names', models.TextField(verbose_name='Other names')),
                ('main', models.TextField(verbose_name='Main content')),
                ('views', models.PositiveBigIntegerField(verbose_name='Views number')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Article category',
                'verbose_name_plural': 'Article categories',
            },
        ),
        migrations.CreateModel(
            name='ArticleImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Image title')),
                ('img', models.ImageField(upload_to='article_imgs', verbose_name='Image')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Article image',
                'verbose_name_plural': 'Article images',
            },
        ),
        migrations.CreateModel(
            name='ArticleSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_article', models.CharField(max_length=40, verbose_name="Target article's name")),
                ('nickname', models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='')),
                ('realName', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='')),
                ('race', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='')),
                ('parents', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='')),
                ('couple', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='')),
                ('age', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='')),
                ('gender', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='')),
                ('favourite_food', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='')),
                ('favourite_color', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='')),
                ('civil_state', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='')),
                ('height', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='')),
                ('weight', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='')),
                ('birthdate', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='')),
                ('birthplace', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='')),
                ('begin_date', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='')),
                ('end_date', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='')),
                ('date', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='')),
                ('year', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='')),
                ('created_by', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='')),
                ('nacionality', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='')),
                ('status', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='')),
                ('location', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='')),
                ('branch', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='')),
                ('extension', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='')),
                ('population', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='')),
                ('speciality', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='')),
                ('participants_number', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='')),
                ('duration', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='')),
                ('symptoms', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='')),
                ('victims', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='')),
                ('species', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='')),
                ('type', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='')),
                ('result', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='')),
                ('group', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='')),
                ('king', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='')),
                ('ruler', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='')),
            ],
            options={
                'verbose_name': 'Article summary',
                'verbose_name_plural': 'Article summaries',
            },
        ),
        migrations.CreateModel(
            name='SectionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Section type',
                'verbose_name_plural': 'Section types',
            },
        ),
        migrations.CreateModel(
            name='RelatedArticles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=40, verbose_name='Title of target article')),
                ('related', models.ManyToManyField(to='articles.article', verbose_name='Related articles')),
            ],
            options={
                'verbose_name': 'Related articles',
                'verbose_name_plural': 'Related articles',
            },
        ),
        migrations.CreateModel(
            name='ArticleSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Title')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Section text')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Show order')),
                ('visible', models.BooleanField(default=True, verbose_name='Is visible')),
                ('collapse', models.BooleanField(default=False, verbose_name='Is collapse')),
                ('articleType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.sectiontype', verbose_name='Section type')),
                ('images', models.ManyToManyField(blank=True, to='articles.articleimages', verbose_name='Section images')),
                ('targetArticle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article', verbose_name='Target article')),
            ],
            options={
                'verbose_name': 'Article section',
                'verbose_name_plural': 'Article sections',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(to='articles.articlecategory', verbose_name='Category(ies)'),
        ),
        migrations.AddField(
            model_name='article',
            name='images',
            field=models.ManyToManyField(to='articles.articleimages', verbose_name="Article main's images"),
        ),
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.articlesummary', verbose_name='Summary'),
        ),
    ]
