# Generated by Django 4.1.7 on 2023-02-27 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0002_remove_relatedarticles_related_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Title')),
                ('other_names', models.TextField(verbose_name='Other names')),
                ('main', models.TextField(verbose_name='Main content')),
                ('views', models.PositiveBigIntegerField(verbose_name='Views number')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Article category',
                'verbose_name_plural': 'Article categories',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Image title')),
                ('img', models.ImageField(upload_to='article_imgs', verbose_name='Image')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Article image',
                'verbose_name_plural': 'Article images',
            },
        ),
        migrations.CreateModel(
            name='SectionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Section type',
                'verbose_name_plural': 'Section types',
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(default=None, null=True, verbose_name="Article's summary")),
                ('article', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
            ],
            options={
                'verbose_name': 'Article summary',
                'verbose_name_plural': 'Articles summaries',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Title')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Section text')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Show order')),
                ('visible', models.BooleanField(default=True, verbose_name='Is visible')),
                ('collapse', models.BooleanField(default=False, verbose_name='Is collapse')),
                ('articleType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.sectiontype', verbose_name='Section type')),
                ('images', models.ManyToManyField(blank=True, to='articles.image', verbose_name='Section images')),
                ('targetArticle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article', verbose_name='Target article')),
            ],
            options={
                'verbose_name': 'Article section',
                'verbose_name_plural': 'Article sections',
            },
        ),
        migrations.CreateModel(
            name='RelatedArticles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=40, verbose_name='Title of target article')),
                ('related', models.ManyToManyField(to='articles.article', verbose_name='Related articles')),
            ],
            options={
                'verbose_name': 'Related articles',
                'verbose_name_plural': 'Related articles',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(to='articles.category', verbose_name='Categories'),
        ),
        migrations.AddField(
            model_name='article',
            name='images',
            field=models.ManyToManyField(to='articles.image', verbose_name='Article main image(s)'),
        ),
    ]
