# Generated by Django 4.1.7 on 2023-02-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='views',
            field=models.PositiveBigIntegerField(null=True, verbose_name='Views number'),
        ),
    ]
