# Generated by Django 4.1.7 on 2023-02-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='other_names',
            field=models.TextField(blank=True, null=True, verbose_name='Other names'),
        ),
    ]
