# Generated by Django 4.1.7 on 2023-03-06 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_remove_summary_summary_summary_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='articleType',
            new_name='sectionType',
        ),
    ]
