# Generated by Django 4.1.7 on 2023-03-07 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_rename_articletype_section_sectiontype'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.image', verbose_name='Category image'),
        ),
    ]
