# Generated by Django 4.1.7 on 2023-03-13 15:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_category_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='main',
            field=models.TextField(validators=[django.core.validators.RegexValidator('.[<->]', 'The field contains suspicous content')], verbose_name='Main content'),
        ),
        migrations.AlterField(
            model_name='article',
            name='other_names',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator('.[<->]', 'The field contains suspicous content')], verbose_name='Other names'),
        ),
        migrations.AlterField(
            model_name='section',
            name='content',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator('.[<->]', 'The field contains suspicous content')], verbose_name='Section text'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='content',
            field=models.TextField(default=None, null=True, validators=[django.core.validators.RegexValidator('.[<->]', 'The field contains suspicous content')], verbose_name="Article's summary content"),
        ),
    ]
