# Generated by Django 4.1.7 on 2023-03-22 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_alter_article_main_alter_article_other_names_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='article',
        ),
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.summary', verbose_name='Summary'),
        ),
    ]
