# Generated by Django 4.1.7 on 2023-04-04 21:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_summary_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='content',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator('.[<->]', 'The field contains suspicous content', inverse_match=True)], verbose_name='Section text. To create a list use #; as separator'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='content',
            field=models.TextField(default='', null=True, validators=[django.core.validators.RegexValidator('.[<->]', 'The field contains suspicous content', inverse_match=True)], verbose_name="Summary's content. Follow this format: name1:value1;name2:value2 \n\n Place #C before any name to set it as censored: #Cstatus:alive"),
        ),
        migrations.AlterField(
            model_name='summary',
            name='title',
            field=models.CharField(max_length=40, verbose_name='Title'),
        ),
    ]
