# Generated by Django 4.1.7 on 2023-03-22 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_remove_summary_article_article_summary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0002_alter_comment_content_author_comment_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
        migrations.AlterField(
            model_name='author',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='comments.author', verbose_name='Registered author'),
        ),
        migrations.CreateModel(
            name='FavouriteArticles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articles', models.ManyToManyField(to='articles.article', verbose_name='Favourite articles')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comments.author', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Favourite articles',
                'verbose_name_plural': 'Favourite articles',
            },
        ),
    ]
