# Generated by Django 4.1.7 on 2023-03-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_alter_favouritearticles_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='bloqued',
            field=models.BooleanField(default=False, verbose_name='Is bloqued'),
        ),
    ]
