# Generated by Django 4.1.7 on 2023-02-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('icon', models.ImageField(upload_to='contact_icons', verbose_name='Icon')),
                ('link', models.URLField(verbose_name='URL')),
            ],
        ),
    ]
